"""Quality-assurance helpers used by release and visual regression tests."""

from medimager.qa.visual_regression import (
    DEFAULT_VISIBILITY_SCALE_FACTORS,
    BaselineUpdateNotAllowed,
    GuiHeartbeatProbe,
    VisibilityCheckResult,
    VisibilityRunReport,
    VisualBaselineStore,
    VisualDiffMetrics,
    VisualDiffThresholds,
    VisualRegressionHarness,
    VisualRunMode,
    VisualRunReport,
    VisualScenario,
    VisualScenarioResult,
    assert_visual_match,
    capture_widget_surface,
    check_widget_visibility_at_scale,
    compare_images,
    default_v26_manifest_metadata,
    default_v26_scenarios,
    find_visibility_violations,
    run_visibility_matrix,
    save_diff_image,
)
from medimager.qa.visual_surfaces import (
    RealMedImagerSurfaceProvider,
    VisualWorkbenchShell,
    critical_widgets_for_surface,
)

__all__ = [
    "DEFAULT_VISIBILITY_SCALE_FACTORS",
    "BaselineUpdateNotAllowed",
    "GuiHeartbeatProbe",
    "RealMedImagerSurfaceProvider",
    "VisibilityCheckResult",
    "VisibilityRunReport",
    "VisualBaselineStore",
    "VisualWorkbenchShell",
    "VisualDiffMetrics",
    "VisualDiffThresholds",
    "VisualRegressionHarness",
    "VisualRunMode",
    "VisualRunReport",
    "VisualScenario",
    "VisualScenarioResult",
    "assert_visual_match",
    "capture_widget_surface",
    "check_widget_visibility_at_scale",
    "compare_images",
    "critical_widgets_for_surface",
    "default_v26_manifest_metadata",
    "default_v26_scenarios",
    "find_visibility_violations",
    "run_visibility_matrix",
    "save_diff_image",
]
