name = "radiant"
border_color = "#FF0F20"      # Yellow
fill_color = "#FFF180"     # Semi-transparent yellow
selected_color = "#FF0000"   # Red
anchor_color = "#FF0000"     # Red
border_width = 2
anchor_size = 8 

# 信息板设置
info_bg_color = "#418426"    # Semi-transparent black
info_text_color = "#FFEC21" 
info_border_color = "#418426" 
info_font_size = 4
info_radius = 0
info_padding = 8
info_precision = 1
info_auto_hide = true 