name = "默认"
line_color = "#000080"        # Green
anchor_color = "#000080"     # Green
text_color = "#000080"       # White
background_color = "#000080" # Semi-transparent black
line_width = 2
anchor_size = 8
font_size = 14 