#!/usr/bin/env python3
"""
MedImager 自动化发布脚本

此脚本自动化构建 MedImager 的发布版本，包括：
1. 清理旧的构建文件
2. 使用 PyInstaller 打包应用程序
3. 创建发布包
4. 生成版本信息
"""

import os
import sys
import shutil
import subprocess
import zipfile
from pathlib import Path
from datetime import datetime
import toml

BUILD_INFO_PATH = Path('medimager/_build_info.py')


def get_project_info():
    """从 pyproject.toml 获取项目信息"""
    try:
        with open('pyproject.toml', 'r', encoding='utf-8') as f:
            config = toml.load(f)
        
        project = config.get('project', {})
        return {
            'name': project.get('name', 'medimager'),
            'version': project.get('version', '1.0.0'),
            'description': project.get('description', '')
        }
    except Exception as e:
        print(f"警告: 无法读取项目信息: {e}")
        return {'name': 'medimager', 'version': '1.0.0', 'description': ''}


def get_latest_changelog():
    """读取最近一次 release changelog，用于构建信息和版本文件。"""
    changelog_path = Path('CHANGELOG.md')
    if not changelog_path.exists():
        return '暂无 release changelog。'

    lines = changelog_path.read_text(encoding='utf-8').splitlines()
    start = None
    for index, line in enumerate(lines):
        if line.startswith('## '):
            start = index
            break

    if start is None:
        return changelog_path.read_text(encoding='utf-8').strip() or '暂无 release changelog。'

    end = len(lines)
    for index in range(start + 1, len(lines)):
        if lines[index].startswith('## '):
            end = index
            break

    return '\n'.join(lines[start:end]).strip() or '暂无 release changelog。'


def generate_release_notes(version, prerelease=True):
    """根据当前 git 历史生成本次 release notes 和 changelog entry。"""
    release_type = 'Preview Release' if prerelease else 'Stable Release'
    release_date = datetime.now().strftime('%Y-%m-%d')
    commit_header, commits = get_release_commits(version)

    features = """- 研究与教学用途的基础 2D DICOM 查看器
- 支持 DICOM 文件/文件夹加载、普通图片加载、多视图显示和基础测量
- 支持 ROI 统计、窗宽窗位、当前视图截图导出和当前切片图像导出
- Release 构建会在关于对话框中显示版本、项目地址和最近一次 release changelog"""

    usage = """1. 下载并解压 ZIP 文件
2. 运行 MedImager.exe
3. 通过菜单打开 DICOM 文件、DICOM 文件夹或普通图片
4. 使用窗宽窗位、ROI、测量和导出工具完成基础查看与分析"""

    release_notes = f"""## MedImager v{version} - {release_type}

### 特性
{features}

### 使用方法
{usage}

### 本次 Release Commit 记录
{commit_header}

{commits}
"""

    changelog_entry = f"""## {version} - {release_date}

### 特性
{features}

### 使用方法
{usage}

### 本次 Release Commit 记录
{commit_header}

{commits}
"""

    return release_notes.strip(), changelog_entry.strip()


def get_release_commits(version):
    """获取上一个 tag 到当前 HEAD 的 commit 记录。"""
    current_tag = f'v{version}'
    try:
        tags_result = subprocess.run(
            ['git', 'tag', '--sort=-creatordate'],
            check=True,
            capture_output=True,
            text=True,
            encoding='utf-8'
        )
        tags = [tag.strip() for tag in tags_result.stdout.splitlines() if tag.strip()]
        previous_tag = next((tag for tag in tags if tag != current_tag), None)

        if previous_tag:
            commit_range = f'{previous_tag}..HEAD'
            commit_header = f'从 `{previous_tag}` 到 `{current_tag}`'
        else:
            commit_range = 'HEAD'
            commit_header = '当前历史记录'

        commits_result = subprocess.run(
            ['git', 'log', commit_range, '--pretty=format:- %h %s (%an)'],
            check=True,
            capture_output=True,
            text=True,
            encoding='utf-8'
        )
        commits = commits_result.stdout.strip() or '- No commits found.'
        return commit_header, commits
    except Exception as e:
        print(f"警告: 无法生成 commit 记录: {e}")
        return '当前历史记录', '- Commit 记录生成失败，请在 GitHub Release 页面检查。'


def prepend_changelog_entry(version, entry):
    """将本次 release entry 累加到 CHANGELOG.md 顶部，已存在则跳过。"""
    changelog_path = Path('CHANGELOG.md')
    existing = changelog_path.read_text(encoding='utf-8') if changelog_path.exists() else '# Changelog\n'

    if f'## {version} ' in existing:
        print(f"   CHANGELOG.md 已包含 {version}，跳过累加")
        return

    if existing.startswith('# Changelog'):
        lines = existing.splitlines()
        title = lines[0]
        rest = '\n'.join(lines[1:]).strip()
        updated = f'{title}\n\n{entry}\n'
        if rest:
            updated += f'\n{rest}\n'
    else:
        updated = f'# Changelog\n\n{entry}\n\n{existing.strip()}\n'

    changelog_path.write_text(updated, encoding='utf-8')
    print(f"   已累加 CHANGELOG.md: {version}")


def write_build_info(version, changelog):
    """写入构建时元数据，供打包后的关于对话框读取。"""
    BUILD_INFO_PATH.write_text(
        '"""Build-time metadata generated by release/build_release.py."""\n\n'
        f'VERSION = {version!r}\n'
        f'RELEASE_CHANGELOG = {changelog!r}\n',
        encoding='utf-8'
    )


def reset_build_info():
    """恢复源码运行时的空构建元数据。"""
    BUILD_INFO_PATH.write_text(
        '"""Build-time metadata.\n\n'
        'Release workflows may overwrite this file before packaging. Source runs keep\n'
        'these values empty and fall back to pyproject.toml / CHANGELOG.md.\n'
        '"""\n\n'
        'VERSION = ""\n'
        'RELEASE_CHANGELOG = ""\n',
        encoding='utf-8'
    )


def clean_build_dirs():
    """清理构建目录"""
    print("🧹 清理构建目录...")
    dirs_to_clean = ['build', 'dist', '__pycache__']
    
    for dir_name in dirs_to_clean:
        if os.path.exists(dir_name):
            shutil.rmtree(dir_name)
            print(f"   删除: {dir_name}")
    

def find_upx_path():
    """获取 UPX 工具路径
    
    用户可以通过两种方式配置 UPX：
    1. 在函数中预设路径（推荐用于自动化构建）
    2. 运行时交互式输入路径
    
    下载 UPX 工具：https://upx.github.io/
    
    Returns:
        str or None: UPX 工具目录路径，如果不使用 UPX 则返回 None
    """
    # 用户配置区域 - 请在此处填写您的 UPX 路径（可选）
    # 示例: upx_path = 'C:\\tools\\upx-4.2.1-win64'
    upx_path = None  # 请替换为您的 UPX 路径，或保持 None 使用交互式输入
    
    # 如果预设了路径，验证并返回
    if upx_path:
        if os.path.exists(upx_path):
            print(f"   使用预设 UPX 路径: {upx_path}")
            return upx_path
        else:
            print(f"   警告: 预设 UPX 路径不存在: {upx_path}")
            print("   将使用交互式输入...")
    
    # 交互式获取 UPX 路径
    return get_upx_path_interactive()


def get_upx_path_interactive():
    """交互式获取 UPX 路径
    
    Returns:
        str or None: 用户输入的 UPX 路径，或 None 跳过压缩
    """
    print("\n📦 UPX 压缩配置")
    print("UPX 可以显著减小可执行文件大小（通常减少 50-70%）")
    print("下载地址: https://upx.github.io/")
    
    while True:
        choice = input("\n是否使用 UPX 压缩？(y/n/help): ").lower().strip()
        
        if choice in ['n', 'no', '否']:
            print("   跳过 UPX 压缩")
            return None
        elif choice in ['help', 'h', '帮助']:
            print("\n📋 UPX 使用说明:")
            print("1. 访问 https://upx.github.io/ 下载最新版本")
            print("2. 解压到任意目录，例如: C:\\tools\\upx-4.2.1-win64")
            print("3. 输入解压后的完整目录路径")
            print("4. 示例路径:")
            print("   - C:\\tools\\upx-4.2.1-win64")
            print("   - D:\\software\\upx")
            print("   - ./upx (相对路径)")
            continue
        elif choice in ['y', 'yes', '是']:
            break
        else:
            print("   请输入 y(是) 或 n(否)，或输入 help 查看帮助")
            continue
    
    # 获取 UPX 路径
    while True:
        upx_path = input("\n请输入 UPX 工具目录路径 (或输入 'skip' 跳过): ").strip()
        
        if upx_path.lower() in ['skip', '跳过', 'cancel', '取消']:
            print("   跳过 UPX 压缩")
            return None
        
        if not upx_path:
            print("   路径不能为空，请重新输入")
            continue
        
        # 处理引号
        upx_path = upx_path.strip('"\'')
        
        # 验证路径
        if os.path.exists(upx_path):
            # 检查是否包含 upx.exe
            upx_exe = os.path.join(upx_path, 'upx.exe')
            if os.path.exists(upx_exe):
                print(f"   ✅ UPX 路径验证成功: {upx_path}")
                return upx_path
            else:
                print(f"   ⚠️  路径存在但未找到 upx.exe: {upx_exe}")
                retry = input("   是否仍要使用此路径？(y/n): ").lower().strip()
                if retry in ['y', 'yes', '是']:
                    return upx_path
                else:
                    continue
        else:
            print(f"   ❌ 路径不存在: {upx_path}")
            print("   请检查路径是否正确，或输入 'skip' 跳过 UPX 压缩")
            continue


def build_application(project_info, use_upx=True):
    """构建应用程序"""
    print("🔨 开始构建应用程序...")
    
    # 基础命令
    cmd = [
        'uv', 'run', 'pyinstaller',
        '--noconfirm',
        '--onefile',  # 单文件模式
        '--windowed',  # 无控制台窗口
        '--name', 'MedImager',
        '--icon', 'medimager/icons/favicon.ico',
        '--clean',
        '--add-data', 'medimager;medimager/',
        '--add-data', 'pyproject.toml;.',
        '--add-data', 'CHANGELOG.md;.',
        'medimager/main.py'
    ]
    
    # 尝试添加 UPX 压缩
    if use_upx:
        upx_path = find_upx_path()
        if upx_path:
            cmd.extend(['--upx-dir', upx_path])
            print(f"   使用 UPX 压缩: {upx_path}")
        else:
            print("   警告: 未找到 UPX 工具，跳过压缩")
    
    print(f"   执行命令: {' '.join(cmd)}")
    
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        print("✅ 构建成功!")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ 构建失败: {e}")
        print(f"错误输出: {e.stderr}")
        return False


def create_release_package(project_info, changelog):
    """创建发布包"""
    print("📦 创建发布包...")
    
    version = project_info['version']
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    
    # 创建发布目录
    release_dir = f"release_v{version}_{timestamp}"
    os.makedirs(release_dir, exist_ok=True)
    
    # 复制可执行文件
    exe_src = 'dist/MedImager.exe'
    exe_dst = f"{release_dir}/MedImager.exe"
    
    if os.path.exists(exe_src):
        shutil.copy2(exe_src, exe_dst)
        print(f"   复制可执行文件: {exe_dst}")
    else:
        print(f"❌ 找不到可执行文件: {exe_src}")
        return None
    
    # 复制文档文件
    docs_to_copy = ['README.md', 'README_zh.md', 'CHANGELOG.md', 'LICENSE', 'BUILD.md']
    for doc in docs_to_copy:
        if os.path.exists(doc):
            shutil.copy2(doc, release_dir)
            print(f"   复制文档: {doc}")
    
    # 创建版本信息文件
    version_info = f"""MedImager v{version} - Preview Release

构建时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
描述: {project_info['description']}

这是一个预览版本，可能包含未完全测试的功能。
如有问题请反馈到项目仓库。

使用方法:
1. 直接运行 MedImager.exe
2. 支持拖拽 DICOM 文件或文件夹
3. 详细使用说明请参考 README.md

最近一次 Release Changelog:
{changelog}
"""
    
    with open(f"{release_dir}/VERSION.txt", 'w', encoding='utf-8') as f:
        f.write(version_info)
    
    # 创建 ZIP 包
    zip_name = f"MedImager_v{version}_preview_{timestamp}.zip"
    with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(release_dir):
            for file in files:
                file_path = os.path.join(root, file)
                arc_name = os.path.relpath(file_path, release_dir)
                zipf.write(file_path, arc_name)
    
    print(f"✅ 发布包创建完成: {zip_name}")
    return zip_name, release_dir


def main():
    """主函数"""
    print("🚀 MedImager 自动化发布流程")
    print("=" * 50)
    
    # 检查是否在项目根目录
    if not os.path.exists('medimager/main.py'):
        print("❌ 请在项目根目录下运行此脚本")
        sys.exit(1)
    
    # 获取项目信息
    project_info = get_project_info()
    release_notes, changelog_entry = generate_release_notes(project_info['version'])
    print(f"📋 项目: {project_info['name']} v{project_info['version']}")
    
    try:
        # 1. 清理构建目录
        clean_build_dirs()

        # 2. 自动累加 CHANGELOG.md，并写入构建时版本和 release notes
        prepend_changelog_entry(project_info['version'], changelog_entry)
        write_build_info(project_info['version'], release_notes)
        
        # 3. 构建应用程序
        if not build_application(project_info):
            print("❌ 构建失败，终止发布流程")
            sys.exit(1)
        
        # 4. 创建发布包
        result = create_release_package(project_info, release_notes)
        if result:
            zip_name, release_dir = result
            print("\n🎉 发布流程完成!")
            print(f"📁 发布目录: {release_dir}")
            print(f"📦 发布包: {zip_name}")
            print("\n📝 下一步:")
            print("1. 测试可执行文件")
            print("2. 上传到 GitHub Releases")
            print("3. 标记为 Preview Release")
        else:
            print("❌ 创建发布包失败")
            sys.exit(1)
            
    except KeyboardInterrupt:
        print("\n⏹️  用户中断操作")
        sys.exit(1)
    except Exception as e:
        print(f"❌ 发生错误: {e}")
        sys.exit(1)
    finally:
        reset_build_info()


if __name__ == '__main__':
    main()
